package org.plasmacore;

import android.view.KeyEvent;

public class PlasmacoreKeycode
{
  final static public int LEFT_ARROW      =   1;
  final static public int UP_ARROW        =   2;
  final static public int RIGHT_ARROW     =   3;
  final static public int DOWN_ARROW      =   4;

  final static public int BACKSPACE       =   8;
  final static public int TAB             =   9;
  final static public int ENTER           =  10;

  final static public int CAPS_LOCK       =  11;
  final static public int LEFT_SHIFT      =  12;
  final static public int RIGHT_SHIFT     =  13;
  final static public int LEFT_CONTROL    =  14;
  final static public int RIGHT_CONTROL   =  15;
  final static public int LEFT_ALT        =  16;
  final static public int RIGHT_ALT       =  17;

  final static public int LEFT_OS         =  18;
  final static public int RIGHT_OS        =  19;
  final static public int LEFT_WINDOWS    =  LEFT_OS;
  final static public int RIGHT_WINDOWS   =  RIGHT_OS;
  final static public int LEFT_COMMAND    =  LEFT_OS;
  final static public int RIGHT_COMMAND   =  RIGHT_OS;

  final static public int FUNCTION        =  26;
  final static public int ESCAPE          =  27;

  final static public int SPACE           =  32;
  final static public int POUND           =  35;

  final static public int APOSTROPHE      =  39;
  final static public int ASTERISK        =  42;
  final static public int PLUS            =  43;
  final static public int COMMA           =  44;
  final static public int MINUS           =  45;
  final static public int PERIOD          =  46;
  final static public int SLASH           =  47;
  final static public int NUMBER_0        =  48;
  final static public int NUMBER_1        =  49;
  final static public int NUMBER_2        =  50;
  final static public int NUMBER_3        =  51;
  final static public int NUMBER_4        =  52;
  final static public int NUMBER_5        =  53;
  final static public int NUMBER_6        =  54;
  final static public int NUMBER_7        =  55;
  final static public int NUMBER_8        =  56;
  final static public int NUMBER_9        =  57;
  final static public int SEMICOLON       =  59;
  final static public int EQUALS          =  61;

  final static public int AT              =  64;

  final static public int A               =  65;
  final static public int B               =  66;
  final static public int C               =  67;
  final static public int D               =  68;
  final static public int E               =  69;
  final static public int F               =  70;
  final static public int G               =  71;
  final static public int H               =  72;
  final static public int I               =  73;
  final static public int J               =  74;
  final static public int K               =  75;
  final static public int L               =  76;
  final static public int M               =  77;
  final static public int N               =  78;
  final static public int O               =  79;
  final static public int P               =  80;
  final static public int Q               =  81;
  final static public int R               =  82;
  final static public int S               =  83;
  final static public int T               =  84;
  final static public int U               =  85;
  final static public int V               =  86;
  final static public int W               =  87;
  final static public int X               =  88;
  final static public int Y               =  89;
  final static public int Z               =  90;

  final static public int OPEN_BRACKET    =  91;
  final static public int BACKSLASH       =  92;
  final static public int CLOSE_BRACKET   =  93;
  final static public int BACKQUOTE       =  96;

  final static public int NUMPAD_ENTER    = 110;

  final static public int SYS_REQUEST     = 124;
  final static public int SCROLL_LOCK     = 125;
  final static public int BREAK           = 126;

  final static public int DELETE          = 127;
  final static public int INSERT          = 128;
  final static public int HOME            = 129;
  final static public int END             = 130;
  final static public int PAGE_UP         = 131;
  final static public int PAGE_DOWN       = 132;

  final static public int NUMPAD_ASTERISK = 142;
  final static public int NUMPAD_PLUS     = 143;
  final static public int NUMPAD_MINUS    = 145;
  final static public int NUMPAD_PERIOD   = 146;
  final static public int NUMPAD_SLASH    = 147;
  final static public int NUMPAD_0        = 148;
  final static public int NUMPAD_1        = 149;
  final static public int NUMPAD_2        = 150;
  final static public int NUMPAD_3        = 151;
  final static public int NUMPAD_4        = 152;
  final static public int NUMPAD_5        = 153;
  final static public int NUMPAD_6        = 154;
  final static public int NUMPAD_7        = 155;
  final static public int NUMPAD_8        = 156;
  final static public int NUMPAD_9        = 157;
  final static public int NUMPAD_NUM_LOCK = 158;
  final static public int NUMPAD_EQUALS   = 161;

  final static public int F1              = 201;
  final static public int F2              = 202;
  final static public int F3              = 203;
  final static public int F4              = 204;
  final static public int F5              = 205;
  final static public int F6              = 206;
  final static public int F7              = 207;
  final static public int F8              = 208;
  final static public int F9              = 209;
  final static public int F10             = 210;
  final static public int F11             = 211;
  final static public int F12             = 212;
  final static public int F13             = 213;
  final static public int F14             = 214;
  final static public int F15             = 215;
  final static public int F16             = 216;
  final static public int F17             = 217;
  final static public int F18             = 218;
  final static public int F19             = 219;

  static public int fromSyscode( int syscode )
  {
    switch (syscode)
    {
      case KeyEvent.KEYCODE_0:                             return NUMBER_0;
      case KeyEvent.KEYCODE_1:                             return NUMBER_1;
      case KeyEvent.KEYCODE_2:                             return NUMBER_2;
      case KeyEvent.KEYCODE_3:                             return NUMBER_3;
      case KeyEvent.KEYCODE_4:                             return NUMBER_4;
      case KeyEvent.KEYCODE_5:                             return NUMBER_5;
      case KeyEvent.KEYCODE_6:                             return NUMBER_6;
      case KeyEvent.KEYCODE_7:                             return NUMBER_7;
      case KeyEvent.KEYCODE_8:                             return NUMBER_8;
      case KeyEvent.KEYCODE_9:                             return NUMBER_9;

      case KeyEvent.KEYCODE_A:                             return A;
      case KeyEvent.KEYCODE_U:                             return U;
      case KeyEvent.KEYCODE_V:                             return V;
      case KeyEvent.KEYCODE_W:                             return W;
      case KeyEvent.KEYCODE_X:                             return X;
      case KeyEvent.KEYCODE_Y:                             return Y;
      case KeyEvent.KEYCODE_Z:                             return Z;
      case KeyEvent.KEYCODE_B:                             return B;
      case KeyEvent.KEYCODE_C:                             return C;
      case KeyEvent.KEYCODE_D:                             return D;
      case KeyEvent.KEYCODE_E:                             return E;
      case KeyEvent.KEYCODE_F:                             return F;
      case KeyEvent.KEYCODE_G:                             return G;
      case KeyEvent.KEYCODE_H:                             return H;
      case KeyEvent.KEYCODE_I:                             return I;
      case KeyEvent.KEYCODE_J:                             return J;
      case KeyEvent.KEYCODE_K:                             return K;
      case KeyEvent.KEYCODE_L:                             return L;
      case KeyEvent.KEYCODE_M:                             return M;
      case KeyEvent.KEYCODE_N:                             return N;
      case KeyEvent.KEYCODE_O:                             return O;
      case KeyEvent.KEYCODE_P:                             return P;
      case KeyEvent.KEYCODE_Q:                             return Q;
      case KeyEvent.KEYCODE_R:                             return R;
      case KeyEvent.KEYCODE_S:                             return S;
      case KeyEvent.KEYCODE_T:                             return T;

      case KeyEvent.KEYCODE_ALT_LEFT:                      return LEFT_ALT;
      case KeyEvent.KEYCODE_ALT_RIGHT:                     return RIGHT_ALT;
      case KeyEvent.KEYCODE_APOSTROPHE:                    return APOSTROPHE;
      case KeyEvent.KEYCODE_AT:                            return AT;
      case KeyEvent.KEYCODE_BACK:                          return ESCAPE;
      case KeyEvent.KEYCODE_BACKSLASH:                     return BACKSLASH;
      case KeyEvent.KEYCODE_CAPS_LOCK:                     return CAPS_LOCK;
      case KeyEvent.KEYCODE_COMMA:                         return COMMA;
      case KeyEvent.KEYCODE_CTRL_LEFT:                     return LEFT_CONTROL;
      case KeyEvent.KEYCODE_CTRL_RIGHT:                    return RIGHT_CONTROL;
      case KeyEvent.KEYCODE_DEL:                           return DELETE;
      case KeyEvent.KEYCODE_ENTER:                         return ENTER;
      case KeyEvent.KEYCODE_EQUALS:                        return EQUALS;
      case KeyEvent.KEYCODE_ESCAPE:                        return ESCAPE;
      case KeyEvent.KEYCODE_F1:                            return F1;
      case KeyEvent.KEYCODE_F10:                           return F10;
      case KeyEvent.KEYCODE_F11:                           return F11;
      case KeyEvent.KEYCODE_F12:                           return F12;
      case KeyEvent.KEYCODE_F2:                            return F2;
      case KeyEvent.KEYCODE_F3:                            return F3;
      case KeyEvent.KEYCODE_F4:                            return F4;
      case KeyEvent.KEYCODE_F5:                            return F5;
      case KeyEvent.KEYCODE_F6:                            return F6;
      case KeyEvent.KEYCODE_F7:                            return F7;
      case KeyEvent.KEYCODE_F8:                            return F8;
      case KeyEvent.KEYCODE_F9:                            return F9;
      case KeyEvent.KEYCODE_FUNCTION:                      return FUNCTION;
      case KeyEvent.KEYCODE_GRAVE:                         return BACKQUOTE;
      case KeyEvent.KEYCODE_HOME:                          return HOME;
      case KeyEvent.KEYCODE_INSERT:                        return INSERT;
      case KeyEvent.KEYCODE_LEFT_BRACKET:                  return OPEN_BRACKET;
      case KeyEvent.KEYCODE_MENU:                          return F1;
      case KeyEvent.KEYCODE_MOVE_HOME:                     return HOME;  // Note: same as response to KEYCODE_HOME above
      case KeyEvent.KEYCODE_META_LEFT:                     return LEFT_OS;
      case KeyEvent.KEYCODE_META_RIGHT:                    return RIGHT_OS;
      case KeyEvent.KEYCODE_MINUS:                         return MINUS;
      case KeyEvent.KEYCODE_MOVE_END:                      return END;
      case KeyEvent.KEYCODE_NUM:                           return NUMPAD_NUM_LOCK;
      case KeyEvent.KEYCODE_NUMPAD_0:                      return NUMPAD_0;
      case KeyEvent.KEYCODE_NUMPAD_1:                      return NUMPAD_1;
      case KeyEvent.KEYCODE_NUMPAD_2:                      return NUMPAD_2;
      case KeyEvent.KEYCODE_NUMPAD_3:                      return NUMPAD_3;
      case KeyEvent.KEYCODE_NUMPAD_4:                      return NUMPAD_4;
      case KeyEvent.KEYCODE_NUMPAD_5:                      return NUMPAD_5;
      case KeyEvent.KEYCODE_NUMPAD_6:                      return NUMPAD_6;
      case KeyEvent.KEYCODE_NUMPAD_7:                      return NUMPAD_7;
      case KeyEvent.KEYCODE_NUMPAD_8:                      return NUMPAD_8;
      case KeyEvent.KEYCODE_NUMPAD_9:                      return NUMPAD_9;
      case KeyEvent.KEYCODE_NUMPAD_ADD:                    return NUMPAD_PLUS;
      case KeyEvent.KEYCODE_NUMPAD_DIVIDE:                 return NUMPAD_SLASH;
      case KeyEvent.KEYCODE_NUMPAD_DOT:                    return NUMPAD_PERIOD;
      case KeyEvent.KEYCODE_NUMPAD_ENTER:                  return NUMPAD_ENTER;
      case KeyEvent.KEYCODE_NUMPAD_EQUALS:                 return NUMPAD_EQUALS;
      case KeyEvent.KEYCODE_NUMPAD_MULTIPLY:               return NUMPAD_ASTERISK;
      case KeyEvent.KEYCODE_NUMPAD_SUBTRACT:               return NUMPAD_MINUS;
      case KeyEvent.KEYCODE_PAGE_DOWN:                     return PAGE_DOWN;
      case KeyEvent.KEYCODE_PAGE_UP:                       return PAGE_UP;
      case KeyEvent.KEYCODE_PLUS:                          return PLUS;
      case KeyEvent.KEYCODE_POUND:                         return POUND;
      case KeyEvent.KEYCODE_RIGHT_BRACKET:                 return CLOSE_BRACKET;
      case KeyEvent.KEYCODE_SCROLL_LOCK:                   return SCROLL_LOCK;
      case KeyEvent.KEYCODE_SEMICOLON:                     return SEMICOLON;
      case KeyEvent.KEYCODE_SHIFT_LEFT:                    return LEFT_SHIFT;
      case KeyEvent.KEYCODE_SHIFT_RIGHT:                   return RIGHT_SHIFT;
      case KeyEvent.KEYCODE_SLASH:                         return SLASH;
      case KeyEvent.KEYCODE_SPACE:                         return SPACE;
      case KeyEvent.KEYCODE_STAR:                          return ASTERISK;
      case KeyEvent.KEYCODE_TAB:                           return TAB;

      //case KeyEvent.KEYCODE_ALL_APPS:                      return 0;
      //case KeyEvent.KEYCODE_APP_SWITCH:                    return 0;
      //case KeyEvent.KEYCODE_ASSIST:                        return 0;
      //case KeyEvent.KEYCODE_AVR_INPUT:                     return 0;
      //case KeyEvent.KEYCODE_AVR_POWER:                     return 0;
      //case KeyEvent.KEYCODE_11:                            return 0;
      //case KeyEvent.KEYCODE_12:                            return 0;
      //case KeyEvent.KEYCODE_3D_MODE:                       return 0;
      //case KeyEvent.KEYCODE_BOOKMARK:                      return 0;
      //case KeyEvent.KEYCODE_BREAK:                         return 0;
      //case KeyEvent.KEYCODE_BRIGHTNESS_DOWN:               return 0;
      //case KeyEvent.KEYCODE_BRIGHTNESS_UP:                 return 0;
      //case KeyEvent.KEYCODE_BUTTON_1:                      return 0;
      //case KeyEvent.KEYCODE_BUTTON_10:                     return 0;
      //case KeyEvent.KEYCODE_BUTTON_11:                     return 0;
      //case KeyEvent.KEYCODE_BUTTON_12:                     return 0;
      //case KeyEvent.KEYCODE_BUTTON_13:                     return 0;
      //case KeyEvent.KEYCODE_BUTTON_14:                     return 0;
      //case KeyEvent.KEYCODE_BUTTON_15:                     return 0;
      //case KeyEvent.KEYCODE_BUTTON_16:                     return 0;
      //case KeyEvent.KEYCODE_BUTTON_2:                      return 0;
      //case KeyEvent.KEYCODE_BUTTON_3:                      return 0;
      //case KeyEvent.KEYCODE_BUTTON_4:                      return 0;
      //case KeyEvent.KEYCODE_BUTTON_5:                      return 0;
      //case KeyEvent.KEYCODE_BUTTON_6:                      return 0;
      //case KeyEvent.KEYCODE_BUTTON_7:                      return 0;
      //case KeyEvent.KEYCODE_BUTTON_8:                      return 0;
      //case KeyEvent.KEYCODE_BUTTON_9:                      return 0;
      //case KeyEvent.KEYCODE_BUTTON_A:                      return 0;
      //case KeyEvent.KEYCODE_BUTTON_B:                      return 0;
      //case KeyEvent.KEYCODE_BUTTON_C:                      return 0;
      //case KeyEvent.KEYCODE_BUTTON_L1:                     return 0;
      //case KeyEvent.KEYCODE_BUTTON_L2:                     return 0;
      //case KeyEvent.KEYCODE_BUTTON_MODE:                   return 0;
      //case KeyEvent.KEYCODE_BUTTON_R1:                     return 0;
      //case KeyEvent.KEYCODE_BUTTON_R2:                     return 0;
      //case KeyEvent.KEYCODE_BUTTON_SELECT:                 return 0;
      //case KeyEvent.KEYCODE_BUTTON_START:                  return 0;
      //case KeyEvent.KEYCODE_BUTTON_THUMBL:                 return 0;
      //case KeyEvent.KEYCODE_BUTTON_THUMBR:                 return 0;
      //case KeyEvent.KEYCODE_BUTTON_X:                      return 0;
      //case KeyEvent.KEYCODE_BUTTON_Y:                      return 0;
      //case KeyEvent.KEYCODE_BUTTON_Z:                      return 0;
      //case KeyEvent.KEYCODE_CALCULATOR:                    return 0;
      //case KeyEvent.KEYCODE_CALENDAR:                      return 0;
      //case KeyEvent.KEYCODE_CALL:                          return 0;
      //case KeyEvent.KEYCODE_CAMERA:                        return 0;
      //case KeyEvent.KEYCODE_CAPTIONS:                      return 0;
      //case KeyEvent.KEYCODE_CHANNEL_DOWN:                  return 0;
      //case KeyEvent.KEYCODE_CHANNEL_UP:                    return 0;
      //case KeyEvent.KEYCODE_CLEAR:                         return 0;
      //case KeyEvent.KEYCODE_CONTACTS:                      return 0;
      //case KeyEvent.KEYCODE_COPY:                          return 0;
      //case KeyEvent.KEYCODE_CUT:                           return 0;
      //case KeyEvent.KEYCODE_DPAD_CENTER:                   return 0;
      //case KeyEvent.KEYCODE_DPAD_DOWN:                     return 0;
      //case KeyEvent.KEYCODE_DPAD_DOWN_LEFT:                return 0;
      //case KeyEvent.KEYCODE_DPAD_DOWN_RIGHT:               return 0;
      //case KeyEvent.KEYCODE_DPAD_LEFT:                     return 0;
      //case KeyEvent.KEYCODE_DPAD_RIGHT:                    return 0;
      //case KeyEvent.KEYCODE_DPAD_UP:                       return 0;
      //case KeyEvent.KEYCODE_DPAD_UP_LEFT:                  return 0;
      //case KeyEvent.KEYCODE_DPAD_UP_RIGHT:                 return 0;
      //case KeyEvent.KEYCODE_DVR:                           return 0;
      //case KeyEvent.KEYCODE_EISU:                          return 0;
      //case KeyEvent.KEYCODE_ENDCALL:                       return 0;
      //case KeyEvent.KEYCODE_ENVELOPE:                      return 0;
      //case KeyEvent.KEYCODE_EXPLORER:                      return 0;
      //case KeyEvent.KEYCODE_FOCUS:                         return 0;
      //case KeyEvent.KEYCODE_FORWARD:                       return 0;
      //case KeyEvent.KEYCODE_FORWARD_DEL:                   return 0;
      //case KeyEvent.KEYCODE_GUIDE:                         return 0;
      //case KeyEvent.KEYCODE_HEADSETHOOK:                   return 0;
      //case KeyEvent.KEYCODE_HELP:                          return 0;
      //case KeyEvent.KEYCODE_HENKAN:                        return 0;
      //case KeyEvent.KEYCODE_INFO:                          return 0;
      //case KeyEvent.KEYCODE_KANA:                          return 0;
      //case KeyEvent.KEYCODE_KATAKANA_HIRAGANA:             return 0;
      //case KeyEvent.KEYCODE_LANGUAGE_SWITCH:               return 0;
      //case KeyEvent.KEYCODE_LAST_CHANNEL:                  return 0;
      //case KeyEvent.KEYCODE_MANNER_MODE:                   return 0;
      //case KeyEvent.KEYCODE_MEDIA_AUDIO_TRACK:             return 0;
      //case KeyEvent.KEYCODE_MEDIA_CLOSE:                   return 0;
      //case KeyEvent.KEYCODE_MEDIA_EJECT:                   return 0;
      //case KeyEvent.KEYCODE_MEDIA_FAST_FORWARD:            return 0;
      //case KeyEvent.KEYCODE_MEDIA_NEXT:                    return 0;
      //case KeyEvent.KEYCODE_MEDIA_PAUSE:                   return 0;
      //case KeyEvent.KEYCODE_MEDIA_PLAY:                    return 0;
      //case KeyEvent.KEYCODE_MEDIA_PLAY_PAUSE:              return 0;
      //case KeyEvent.KEYCODE_MEDIA_PREVIOUS:                return 0;
      //case KeyEvent.KEYCODE_MEDIA_RECORD:                  return 0;
      //case KeyEvent.KEYCODE_MEDIA_REWIND:                  return 0;
      //case KeyEvent.KEYCODE_MEDIA_SKIP_BACKWARD:           return 0;
      //case KeyEvent.KEYCODE_MEDIA_SKIP_FORWARD:            return 0;
      //case KeyEvent.KEYCODE_MEDIA_STEP_BACKWARD:           return 0;
      //case KeyEvent.KEYCODE_MEDIA_STEP_FORWARD:            return 0;
      //case KeyEvent.KEYCODE_MEDIA_STOP:                    return 0;
      //case KeyEvent.KEYCODE_MEDIA_TOP_MENU:                return 0;
      //case KeyEvent.KEYCODE_MUHENKAN:                      return 0;
      //case KeyEvent.KEYCODE_MUSIC:                         return 0;
      //case KeyEvent.KEYCODE_MUTE:                          return 0;
      //case KeyEvent.KEYCODE_NAVIGATE_IN:                   return 0;
      //case KeyEvent.KEYCODE_NAVIGATE_NEXT:                 return 0;
      //case KeyEvent.KEYCODE_NAVIGATE_OUT:                  return 0;
      //case KeyEvent.KEYCODE_NAVIGATE_PREVIOUS:             return 0;
      //case KeyEvent.KEYCODE_NOTIFICATION:                  return 0;
      //case KeyEvent.KEYCODE_NUMPAD_COMMA:                  return 0;
      //case KeyEvent.KEYCODE_NUMPAD_LEFT_PAREN:             return 0;
      //case KeyEvent.KEYCODE_NUMPAD_RIGHT_PAREN:            return 0;
      //case KeyEvent.KEYCODE_NUM_LOCK:                      return 0;
      //case KeyEvent.KEYCODE_PAIRING:                       return 0;
      //case KeyEvent.KEYCODE_PASTE:                         return 0;
      //case KeyEvent.KEYCODE_PERIOD:                        return 0;
      //case KeyEvent.KEYCODE_PICTSYMBOLS:                   return 0;
      //case KeyEvent.KEYCODE_POWER:                         return 0;
      //case KeyEvent.KEYCODE_PROG_BLUE:                     return 0;
      //case KeyEvent.KEYCODE_PROG_GREEN:                    return 0;
      //case KeyEvent.KEYCODE_PROG_RED:                      return 0;
      //case KeyEvent.KEYCODE_PROG_YELLOW:                   return 0;
      //case KeyEvent.KEYCODE_REFRESH:                       return 0;
      //case KeyEvent.KEYCODE_RO:                            return 0;
      //case KeyEvent.KEYCODE_SEARCH:                        return 0;
      //case KeyEvent.KEYCODE_SETTINGS:                      return 0;
      //case KeyEvent.KEYCODE_SLEEP:                         return 0;
      //case KeyEvent.KEYCODE_SOFT_LEFT:                     return 0;
      //case KeyEvent.KEYCODE_SOFT_RIGHT:                    return 0;
      //case KeyEvent.KEYCODE_SOFT_SLEEP:                    return 0;
      //case KeyEvent.KEYCODE_STB_INPUT:                     return 0;
      //case KeyEvent.KEYCODE_STB_POWER:                     return 0;
      //case KeyEvent.KEYCODE_STEM_1:                        return 0;
      //case KeyEvent.KEYCODE_STEM_2:                        return 0;
      //case KeyEvent.KEYCODE_STEM_3:                        return 0;
      //case KeyEvent.KEYCODE_STEM_PRIMARY:                  return 0;
      //case KeyEvent.KEYCODE_SWITCH_CHARSET:                return 0;
      //case KeyEvent.KEYCODE_SYM:                           return 0;
      //case KeyEvent.KEYCODE_SYSRQ:                         return 0;
      //case KeyEvent.KEYCODE_SYSTEM_NAVIGATION_DOWN:        return 0;
      //case KeyEvent.KEYCODE_SYSTEM_NAVIGATION_LEFT:        return 0;
      //case KeyEvent.KEYCODE_SYSTEM_NAVIGATION_RIGHT:       return 0;
      //case KeyEvent.KEYCODE_SYSTEM_NAVIGATION_UP:          return 0;
      //case KeyEvent.KEYCODE_TV:                            return 0;
      //case KeyEvent.KEYCODE_TV_ANTENNA_CABLE:              return 0;
      //case KeyEvent.KEYCODE_TV_AUDIO_DESCRIPTION:          return 0;
      //case KeyEvent.KEYCODE_TV_AUDIO_DESCRIPTION_MIX_DOWN: return 0;
      //case KeyEvent.KEYCODE_TV_AUDIO_DESCRIPTION_MIX_UP:   return 0;
      //case KeyEvent.KEYCODE_TV_CONTENTS_MENU:              return 0;
      //case KeyEvent.KEYCODE_TV_DATA_SERVICE:               return 0;
      //case KeyEvent.KEYCODE_TV_INPUT:                      return 0;
      //case KeyEvent.KEYCODE_TV_INPUT_COMPONENT_1:          return 0;
      //case KeyEvent.KEYCODE_TV_INPUT_COMPONENT_2:          return 0;
      //case KeyEvent.KEYCODE_TV_INPUT_COMPOSITE_1:          return 0;
      //case KeyEvent.KEYCODE_TV_INPUT_COMPOSITE_2:          return 0;
      //case KeyEvent.KEYCODE_TV_INPUT_HDMI_1:               return 0;
      //case KeyEvent.KEYCODE_TV_INPUT_HDMI_2:               return 0;
      //case KeyEvent.KEYCODE_TV_INPUT_HDMI_3:               return 0;
      //case KeyEvent.KEYCODE_TV_INPUT_HDMI_4:               return 0;
      //case KeyEvent.KEYCODE_TV_INPUT_VGA_1:                return 0;
      //case KeyEvent.KEYCODE_TV_MEDIA_CONTEXT_MENU:         return 0;
      //case KeyEvent.KEYCODE_TV_NETWORK:                    return 0;
      //case KeyEvent.KEYCODE_TV_NUMBER_ENTRY:               return 0;
      //case KeyEvent.KEYCODE_TV_POWER:                      return 0;
      //case KeyEvent.KEYCODE_TV_RADIO_SERVICE:              return 0;
      //case KeyEvent.KEYCODE_TV_SATELLITE:                  return 0;
      //case KeyEvent.KEYCODE_TV_SATELLITE_BS:               return 0;
      //case KeyEvent.KEYCODE_TV_SATELLITE_CS:               return 0;
      //case KeyEvent.KEYCODE_TV_SATELLITE_SERVICE:          return 0;
      //case KeyEvent.KEYCODE_TV_TELETEXT:                   return 0;
      //case KeyEvent.KEYCODE_TV_TERRESTRIAL_ANALOG:         return 0;
      //case KeyEvent.KEYCODE_TV_TERRESTRIAL_DIGITAL:        return 0;
      //case KeyEvent.KEYCODE_TV_TIMER_PROGRAMMING:          return 0;
      //case KeyEvent.KEYCODE_TV_ZOOM_MODE:                  return 0;
      //case KeyEvent.KEYCODE_UNKNOWN:                       return 0;
      //case KeyEvent.KEYCODE_VOICE_ASSIST:                  return 0;
      //case KeyEvent.KEYCODE_VOLUME_DOWN:                   return 0;
      //case KeyEvent.KEYCODE_VOLUME_MUTE:                   return 0;
      //case KeyEvent.KEYCODE_VOLUME_UP:                     return 0;
      //case KeyEvent.KEYCODE_WAKEUP:                        return 0;
      //case KeyEvent.KEYCODE_WINDOW:                        return 0;
      //case KeyEvent.KEYCODE_YEN:                           return 0;
      //case KeyEvent.KEYCODE_ZENKAKU_HANKAKU:               return 0;
      //case KeyEvent.KEYCODE_ZOOM_IN:                       return 0;
      //case KeyEvent.KEYCODE_ZOOM_OUT:                      return 0;

      default:                                             return 0;

    }
  }
}
